# Generated by Django 5.1.6 on 2025-02-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
