# Generated by Django 5.1.6 on 2025-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_delete_doctor_remove_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('brain', 'Brain'), ('kidney', 'Kidney'), ('lung', 'Lung')], default=False, max_length=10)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
