# Generated by Django 5.1.6 on 2025-03-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(default='18'),
        ),
    ]
