# Generated by Django 5.1.6 on 2025-03-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='profile/'),
        ),
    ]
